dubbo:
  application:
    #项目名字
    name: order-service
  protocol:
    # 通讯协议
    name: dubbo
    # 端口号 设置端口为 -1 表示 dubbo 自动扫描并使用可用端口（从20880开始递增），避免了端口冲突的问题。
    port: -1
  registry:
    # 注册地址
    address: nacos://192.168.187.100:8848

server:
  port: 8085
