dubbo:
  application:
    #项目名字
    name: payment-service
  protocol:
    # 通讯协议
    name: dubbo
    # 端口号 设置端口为 -1 表示 dubbo 自动扫描并使用可用端口（从20880开始递增），避免了端口冲突的问题。
    port: -1
  registry:
    # 注册地址
    address: nacos://192.168.187.100:8848


server:
  port: 8004

#配置数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.187.100:3306/dubbo_test?serverTimezone=UTC
    username: root
    password: root
#配置MybatisPlus的日志输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
